### ISSUE TITLE
Add support for deploying to multiple environments

### ISSUE THREAD

**Issue by blkperl** [signalfx/signalfx-detector-syncer#3]
I need the ability to conditionally apply notification rules on an environment variable.

For example 

If prod I want to use the prod account
```
    notifications:
      - type: Pagerduty
        credentialId: PROD_ID
        credentialName: PROD_NAME
```

If dev I want to use the dev account or email notifications
```
    notifications:
      - type: Pagerduty
        credentialId: DEV_ID
        credentialName: DEV_NAME
```

Perhaps you could do something similar to what CloudFormation does with reference conditions

http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-conditions.html
